<?php
if(!defined('ABSPATH'))exit;
class Hooshid_AI{
 public function __construct(){add_action('rest_api_init',[$this,'routes']);}
 public function routes(){register_rest_route('hooshid/v1','/chat',['methods'=>'POST','callback'=>[$this,'chat'],'permission_callback'=>[$this,'permission']]);register_rest_route('hooshid/v1','/books',['methods'=>'GET','callback'=>[$this,'books'],'permission_callback'=>[$this,'permission']]);register_rest_route('hooshid/v1','/books/(?P<id>\\d+)/page/(?P<page>\\d+)',['methods'=>'GET','callback'=>[$this,'page'],'permission_callback'=>[$this,'permission']]);register_rest_route('hooshid/v1','/books/(?P<id>\\d+)/page',['methods'=>'POST','callback'=>[$this,'save_page'],'permission_callback'=>[$this,'permission']]);register_rest_route('hooshid/v1','/command',['methods'=>'POST','callback'=>[$this,'command'],'permission_callback'=>[$this,'permission']]);}
 public function permission(){return is_user_logged_in()&&wp_verify_nonce($_SERVER['HTTP_X_WP_NONCE']??'','wp_rest');}
 private function normalize($s){$s=str_replace(['ي','ى','ك','ۀ','ة','ؤ','إ','أ','ٱ'],['ی','ی','ک','ه','ه','و','ا','ا','ا'],(string)$s);return preg_replace('/\\s+/u',' ',trim($s));}
 private function digits($s){return strtr($s,['۰'=>'0','۱'=>'1','۲'=>'2','۳'=>'3','۴'=>'4','۵'=>'5','۶'=>'6','۷'=>'7','۸'=>'8','۹'=>'9','٠'=>'0','١'=>'1','٢'=>'2','٣'=>'3','٤'=>'4','٥'=>'5','٦'=>'6','٧'=>'7','٨'=>'8','٩'=>'9']);}
 public function books(){return ['books'=>Hooshid_Books::all()];}
 public function page(WP_REST_Request $r){$row=Hooshid_Books::page(absint($r['id']),absint($r['page']));if(!$row)return new WP_Error('not_found','کتاب یا صفحه پیدا نشد',['status'=>404]);$row->pdf_url=wp_get_attachment_url($row->attachment_id);return ['book'=>$row];}
 public function save_page(WP_REST_Request $r){$book=absint($r['id']);$page=absint($r->get_param('page_number'));$text=sanitize_textarea_field($r->get_param('page_text'));if(!$book||$page<1)return new WP_Error('bad_request','اطلاعات صفحه نامعتبر است',['status'=>400]);global $wpdb;$wpdb->replace($wpdb->prefix.'hooshid_book_pages',['book_id'=>$book,'page_number'=>$page,'page_text'=>$text],['%d','%d','%s']);return ['saved'=>true,'book_id'=>$book,'page'=>$page];}
 public function command(WP_REST_Request $r){$q=$this->normalize($this->digits($r->get_param('message')));if(!$q)return new WP_Error('empty_message','فرمان خالی است',['status'=>400]);preg_match('/(?:صفحه|پیج)\\s*(\\d+)/u',$q,$pm);$page=!empty($pm[1])?absint($pm[1]):0;$grades=['اول'=>1,'دوم'=>2,'سوم'=>3,'چهارم'=>4,'پنجم'=>5,'ششم'=>6];$grade=0;foreach($grades as $word=>$num)if(mb_strpos($q,$word)!==false){$grade=$num;break;}if(!$grade&&preg_match('/پایه\\s*(\\d+)/u',$q,$gm))$grade=absint($gm[1]);$books=Hooshid_Books::all();$match=null;foreach($books as $b){if(mb_strpos($q,$this->normalize($b->subject))!==false||mb_strpos($q,$this->normalize($b->title))!==false){if(!$grade||$grade==(int)$b->grade){$match=$b;break;}}}if(!$match&&$grade)foreach($books as $b)if((int)$b->grade===$grade){$match=$b;break;}if($page&&$match)return ['action'=>'open_book_page','book_id'=>(int)$match->id,'grade'=>(int)$match->grade,'subject'=>$match->subject,'page'=>$page,'explain'=>preg_match('/توضیح|شرح|درس/u',$q)===1];return ['action'=>'chat','message'=>$r->get_param('message')];}
 public function chat(WP_REST_Request $r){$key=get_option('hooshid_openai_key','');$model=get_option('hooshid_openai_model','gpt-6-luna');if(!$key)return new WP_Error('no_api_key','کلید OpenAI تنظیم نشده است',['status'=>400]);$message=sanitize_textarea_field($r->get_param('message'));if(!$message)return new WP_Error('empty_message','پیام خالی است',['status'=>400]);$context=sanitize_textarea_field($r->get_param('page_text')??'');$book=sanitize_text_field($r->get_param('book_title')??'');$page=absint($r->get_param('page')??0);$prompt=$message;if($context)$prompt.="\n\nمتن صفحه کتاب:\n".$context."\n\nکتاب: ".$book." | صفحه: ".$page;$res=wp_remote_post('https://api.openai.com/v1/responses',['timeout'=>90,'headers'=>['Authorization'=>'Bearer '.$key,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['model'=>$model,'instructions'=>'تو دستیار آموزشی هوشید هستی. فارسی، روشن و مرحله‌به‌مرحله پاسخ بده. اگر متن صفحه کتاب ارائه شده، برای سؤال مربوط به آن از همان متن به عنوان منبع اصلی استفاده کن.','input'=>$prompt])]);if(is_wp_error($res))return $res;$code=wp_remote_retrieve_response_code($res);$body=json_decode(wp_remote_retrieve_body($res),true);if($code<200||$code>=300)return new WP_Error('openai_error',$body['error']['message']??'خطا در ارتباط با OpenAI',['status'=>502]);$text=$body['output_text']??'';if(!$text&&isset($body['output'])&&is_array($body['output']))foreach($body['output'] as $item)foreach(($item['content']??[]) as $part)if(isset($part['text']))$text.=$part['text'];return $text?['reply'=>$text]:new WP_Error('ai_error','پاسخ معتبر از OpenAI دریافت نشد.',['status'=>502]);}
}